version: "3.8"

services:
  order-service:
    build: ./Order_Service
    container_name: order-service
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      MONGO_URI: "mongodb+srv://prudhvigopasina1999:gPrudhvi7Raj@paymentorderservice.awlddpg.mongodb.net/?retryWrites=true&w=majority&appName=paymentOrderService"

  payment-service:
    build: ./Payment_Service
    container_name: payment-service
    restart: always
    ports:
      - "5001:5001"
    depends_on:
      - order-service
