version: "3.8"

services:
  order-service:
    build: ./Order_Service
    container_name: order-service
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - mongo
      - rabbitmq
    environment:
      MONGO_URI: "mongodb+srv://prudhvigopasina1999:gPrudhvi7Raj@paymentorderservice.awlddpg.mongodb.net/?retryWrites=true&w=majority&appName=paymentOrderService"
      RABBITMQ_URL: "amqp://rabbitmq"

  payment-service:
    build: ./Payment_Service
    container_name: payment-service
    restart: always
    ports:
      - "5001:5001"
    depends_on:
      - order-service
      - rabbitmq
    environment:
      MONGO_URI: "mongodb+srv://prudhvigopasina1999:gPrudhvi7Raj@paymentorderservice.awlddpg.mongodb.net/?retryWrites=true&w=majority&appName=paymentOrderService"
      RABBITMQ_URL: "amqp://guest:guest@rabbitmq:5672/"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: always

  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
